export type ProjectCategory =
  | "commercial"
  | "farmhouse"
  | "residential"
  | "mep"
  | "chemical-proofing"
  | "civil-works";

export type ProjectStatus = "completed" | "ongoing" | "in-progress";

export type Project = {
  slug: string;
  title: string;
  category: ProjectCategory;
  client: string;
  status: ProjectStatus;
  contractValue?: number;
  projectValue?: number;
  location: string;
  description?: string;
  images: string[];
  featured: boolean;
  order: number;
};

export const projects: Project[] = [
  {
    slug: "hassan-nawaz-farmhouse-chakkri",
    title: "Hassan Nawaz Khokhar Farmhouse",
    category: "farmhouse",
    client: "Mr. Hassan Nawaz Khokhar (Businessman)",
    status: "ongoing",
    contractValue: 25,
    projectValue: 120,
    location: "Chakkri, M2, Islamabad",
    description: "Total land 20 Kanal, covered area 15,000 sq. ft.",
    images: [],
    featured: false,
    order: 1,
  },
  {
    slug: "zishan-kalim-farmhouse",
    title: "Zishan Kalim Farmhouse",
    category: "farmhouse",
    client: "Mr. Zeshan Kalim (Businessman)",
    status: "ongoing",
    contractValue: 15,
    projectValue: 150,
    location: "Plot No. 241, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 2,
  },
  {
    slug: "hills-one-bahria-enclave",
    title: "Hills One",
    category: "commercial",
    client: "Mr. Hamayoun (Amanat Group)",
    status: "ongoing",
    contractValue: 50,
    projectValue: 250,
    location: "Bahria Enclave, Islamabad",
    description: "High-rise building (1 Basement + Ground + 5 floors) on 1.2 Kanal.",
    images: [],
    featured: true,
    order: 3,
  },
  {
    slug: "damcon-tower-civic-center",
    title: "Damcon Tower",
    category: "commercial",
    client: "Mr. Tahir Iqbal (Businessman)",
    status: "completed",
    contractValue: 30,
    projectValue: 150,
    location: "Plot #73, Civic Center, Gulberg Greens, Islamabad",
    description: "High-rise building (2 Basements + Ground + 6 floors).",
    images: [],
    featured: true,
    order: 4,
  },
  {
    slug: "residential-house-46-i-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. Tahir Shah (Businessman)",
    status: "completed",
    contractValue: 30,
    projectValue: 30,
    location: "House #46, I Block, Gulberg Greens, Islamabad",
    images: [],
    featured: true,
    order: 5,
  },
  {
    slug: "berg-1-business-square",
    title: "Berg-I Tower",
    category: "commercial",
    client: "Mr. Hamayoun / Mr. Shahbaz (Eelaf Construction)",
    status: "completed",
    contractValue: 28,
    projectValue: 110,
    location: "Plot #C98, Business Square, Gulberg Greens, Islamabad",
    description: "High-rise building (1 Basement + Ground + 6 floors).",
    images: [],
    featured: true,
    order: 6,
  },
  {
    slug: "shopping-mall-g8-4",
    title: "Shopping Mall",
    category: "commercial",
    client: "Mr. Hassan Nawaz Khokhar (Businessman)",
    status: "completed",
    contractValue: 20,
    projectValue: 65,
    location: "Sector G-8/4, Islamabad",
    description: "1 Basement + Ground + 5 floors.",
    images: [],
    featured: false,
    order: 7,
  },
  {
    slug: "farmhouse-d70-gulberg-greens",
    title: "Farm House",
    category: "farmhouse",
    client: "Mr. Saad Nazir",
    status: "completed",
    contractValue: 26,
    projectValue: 120,
    location: "Plot D-70, Gulberg Greens, Islamabad",
    description: "Area: 10 Kanal.",
    images: [],
    featured: false,
    order: 8,
  },
  {
    slug: "farmhouse-a241-gulberg-greens",
    title: "Farm House",
    category: "farmhouse",
    client: "Mr. Zeshan Kaleem (Businessman)",
    status: "completed",
    contractValue: 7,
    projectValue: 7,
    location: "Plot A-241, Gulberg Greens, Islamabad",
    description: "Area: 05 Kanal.",
    images: [],
    featured: false,
    order: 9,
  },
  {
    slug: "farmhouse-c114-gulberg-greens",
    title: "Farm House",
    category: "farmhouse",
    client: "Mr. Rashid Kamal (Ex-Air Marshal)",
    status: "completed",
    contractValue: 10,
    projectValue: 70,
    location: "Plot C-114, Gulberg Greens, Islamabad",
    description: "Area: 05 Kanal.",
    images: [],
    featured: false,
    order: 10,
  },
  {
    slug: "residential-house-201-l-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. Sohaib",
    status: "completed",
    contractValue: 10,
    projectValue: 10,
    location: "House #201, L Block, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 11,
  },
  {
    slug: "residential-house-364-l-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. M. Farooq",
    status: "completed",
    contractValue: 14,
    projectValue: 14,
    location: "House #364, L Block, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 12,
  },
  {
    slug: "residential-house-405-l-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. M. Abrar",
    status: "completed",
    contractValue: 14,
    projectValue: 14,
    location: "House #405, L Block, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 13,
  },
  {
    slug: "residential-house-146-l-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. Farhan",
    status: "completed",
    contractValue: 16,
    projectValue: 16,
    location: "House #146, L Block, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 14,
  },
  {
    slug: "residential-m-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. Hassan",
    status: "completed",
    contractValue: 2.5,
    projectValue: 15,
    location: "M Block, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 15,
  },
  {
    slug: "farmhouse-c69-boundary-wall",
    title: "Farm House Boundary Wall",
    category: "farmhouse",
    client: "Mr. Anees",
    status: "completed",
    contractValue: 10,
    projectValue: 10,
    location: "Plot C-69, Gulberg Greens, Islamabad",
    description: "Area: 10 Kanal.",
    images: [],
    featured: false,
    order: 16,
  },
  {
    slug: "residential-house-899-a-block",
    title: "Residential Building",
    category: "residential",
    client: "Mr. Qasim",
    status: "completed",
    contractValue: 16,
    projectValue: 16,
    location: "House #899, A Block, Gulberg Greens, Islamabad",
    images: [],
    featured: false,
    order: 17,
  },
  {
    slug: "farmhouse-c170-gulberg-greens",
    title: "C-170 Farmhouse",
    category: "farmhouse",
    client: "Mr. Humayo Fargham (Oil & Gas, Iraq)",
    status: "completed",
    contractValue: 25,
    projectValue: 110,
    location: "Plot C-170, Gulberg Greens, Islamabad",
    description: "Area: 05 Kanal.",
    images: [],
    featured: true,
    order: 18,
  },
  {
    slug: "farmhouse-c05-gulberg-green",
    title: "C-05 Farm House",
    category: "farmhouse",
    client: "Mr. Ammad Ahmad (Businessman)",
    status: "completed",
    contractValue: 12,
    projectValue: 12,
    location: "Plot C-05, Gulberg Green, Islamabad",
    description: "Area: 10 Kanal.",
    images: [],
    featured: true,
    order: 19,
  },
  {
    slug: "submersible-sludge-pumps-nowshera",
    title: "Submersible Sludge Pumps",
    category: "mep",
    client: "NTDC",
    status: "completed",
    contractValue: 14,
    projectValue: 14,
    location: "Nowshera, KPK",
    description: "Installation of 2 x 900 GPM submersible sludge pumps.",
    images: [],
    featured: true,
    order: 20,
  },
  {
    slug: "ug-water-tank-chemical-proofing-nowshera",
    title: "UG Water Tank Chemical Proofing",
    category: "chemical-proofing",
    client: "NTDC",
    status: "completed",
    contractValue: 6,
    projectValue: 6,
    location: "Nowshera, KPK",
    description: "Chemical proofing of an underground water tank, capacity 2500 m³.",
    images: [],
    featured: true,
    order: 21,
  },
  {
    slug: "tank-chemical-proofing",
    title: "Tank Chemical Proofing",
    category: "chemical-proofing",
    client: "Not specified",
    status: "completed",
    location: "Islamabad",
    images: [],
    featured: true,
    order: 22,
  },
  {
    slug: "pak-pwd-hissam-water-supply-phase-1",
    title: "Rehabilitation of PAK PWD Drinking Water Supply Scheme",
    category: "civil-works",
    client: "PHE Division, D.I. Khan",
    status: "completed",
    contractValue: 4.5,
    projectValue: 4.5,
    location: "U/C Hissam, D.I. Khan",
    description: "Phase I.",
    images: [],
    featured: false,
    order: 23,
  },
  {
    slug: "pak-pwd-hissam-water-supply-phase-2",
    title: "Rehabilitation of PAK PWD Drinking Water Supply Scheme",
    category: "civil-works",
    client: "PHE Division, D.I. Khan",
    status: "completed",
    contractValue: 5.1,
    projectValue: 5.1,
    location: "U/C Hissam, D.I. Khan",
    description: "Phase II.",
    images: [],
    featured: false,
    order: 24,
  },
  {
    slug: "flood-protection-band-gandi-gaibullah-looni",
    title: "Flood Protection Band",
    category: "civil-works",
    client: "Gomal Zam Irrigation Division, D.I. Khan",
    status: "completed",
    contractValue: 10,
    projectValue: 10,
    location: "Gandi Gaibullah & Looni, D.I. Khan",
    images: [],
    featured: false,
    order: 25,
  },
  {
    slug: "flood-protection-band-gandi-tummani-looni",
    title: "Flood Protection Band",
    category: "civil-works",
    client: "Gomal Zam Irrigation Division, D.I. Khan",
    status: "in-progress",
    contractValue: 10,
    projectValue: 10,
    location: "Gandi Tummani & Looni, D.I. Khan",
    images: [],
    featured: false,
    order: 26,
  },
  {
    slug: "flood-protection-spur-village-looni",
    title: "Flood Protection Spur",
    category: "civil-works",
    client: "Gomal Zam Irrigation Division, D.I. Khan",
    status: "completed",
    contractValue: 7.168,
    projectValue: 7.168,
    location: "Village Looni, D.I. Khan",
    images: [],
    featured: false,
    order: 27,
  },
  {
    slug: "kerb-stone-installation-gulberg-green",
    title: "Kerb Stone Installation & Painting",
    category: "civil-works",
    client: "Gulberg Green, Islamabad",
    status: "completed",
    contractValue: 20,
    projectValue: 20,
    location: "Gulberg Green, Islamabad",
    images: [],
    featured: true,
    order: 28,
  },
  {
    slug: "tuff-tile-installation-jinnah-garden",
    title: "Tuff Tile Installation Works",
    category: "civil-works",
    client: "Jinnah Garden, Islamabad",
    status: "completed",
    contractValue: 10,
    projectValue: 10,
    location: "Jinnah Garden, Islamabad",
    images: [],
    featured: true,
    order: 29,
  },
];
